version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedule-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - OPCACHE_ENABLE=1
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    networks:
      - schedule-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: schedule-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - schedule-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: schedule-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - schedule-network

networks:
  schedule-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
