version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedule-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./uploads:/var/www/public/uploads
      - ./debug:/var/www/debug
    networks:
      - schedule-network
    depends_on:
      - db
    command: >
      bash -c "
        php artisan migrate --force &&
        php-fpm
      "

  nginx:
    image: nginx:alpine
    container_name: schedule-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - schedule-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: schedule-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - schedule-network

networks:
  schedule-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
